name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16'
    - run: npm install
    - name: Run E2E Tests
      env:
        HEADLESS: 'true'
      run: npx wdio run wdio.conf.ts
